package CountingDNANucleotides;

import java.io.*;

public class CountingDNANucleotides {
    public static void main(String[] args) {
	String Sequence = "TGCGCTCTCCGTAAGCACTGAGCCTTAAGAACAAGAGCGAAAGAACTCAGATGAATAATTCAGCGGCATTCACACACGTCTCACTATCCCGATTGCTTGAACCTCGAGGGCACAGCCTCACCGGCCGTAAAAGGTGTTGAGCATGCTACTGGCCGGGAGAGGCATTCTGATCCTGGGCCGTCGCCGAGAAGCAACGGCGCAACAGTATTCAGTGCGACGTCTTTCTTGCGATACCTAACTTGGTCTGGATTAACTGTATATAGGGTGTGAAGTGGGTTATTACACTCAAACATAACCGCCAAACGCTTCGATATGACTAGGTTTAGAGAATTACCTCCGAGCATTGGTAAAGTCTTACGTCCATTGTGCGGTTCGAATTTTCACTACAGGACCGAAAGCCTGACTGGGAGTTAAATTCTGCTTCAGAGGCTGGAAGATTCTCACGGTGTATGGCGAACTTAGATCTGCCGACGACACTCTTATTTCAGCCCCTAAGATCCCGATTGTCAAAAGGTGAGAGTTAGGATCAGCGCTGCTATGCAACTATGGATGAAAGACACAGGTCAGGGCCCCTGTTGATAAATGCGTGACTACTATGTAAACGTACAGATGCGCTTAGTTATTCTCGATTCCCTAGAGGGACACCCCTTTTGTGGGCAGACAACTTCCCAGGGGAATGCCAACGTAATTGCCGCGACTTCCCACAGCGAAATGGCAGCTGCGATATTGTAGTCTTCCATAGAGTAGCGATTAAGGCGAGTCGATTTGCTTCCGGCCGACAAGGTAGTACTGGTCTGCTATATGTCGCAGCGATGTGAAATGAAGCGTGGTCTTTCTATTGTTCCTCTTATCGTCACTTCAATGAGGCATCTACCATAGACGTATTTCTACCAAAACTCTGCGCTGATCTACTCACGCCCGCAATAGGTAGTCT";
	int A = 0;
	int T = 0;
	int C = 0;
	int G = 0;
	int pos = 0;
	Boolean end = true;

	while (end == true) {
	    if (Sequence.substring(pos, pos + 1).equals("T")) {
		System.out.print("U");
		pos++;
	    }
	    if (!Sequence.substring(pos, pos + 1).equals("T")) {
		System.out.print(Sequence.substring(pos, pos + 1));

	    }

	    else {
		end = false;

	    }
	}
    }

}
